[package]
name = "gunda-storage"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gunda-core = { path = "../gunda-core" }
sqlx.workspace = true
time.workspace = true
url.workspace = true
tracing.workspace = true

[dev-dependencies]
gunda-http = { path = "../gunda-http"}
tempfile.workspace = true
tokio = { workspace = true, features = ["net", "io-util", "time"] }
tracing-subscriber.workspace = true